/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReservationIndexRouteImport } from './routes/reservation/index'
import { Route as ReservationIdRouteImport } from './routes/reservation/$id'
import { Route as PaymentIdRouteImport } from './routes/payment/$id'
import { Route as CheckoutIdRouteImport } from './routes/checkout.$id'
import { Route as PaymentPrintIdRouteImport } from './routes/payment/print.$id'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationIndexRoute = ReservationIndexRouteImport.update({
  id: '/reservation/',
  path: '/reservation/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationIdRoute = ReservationIdRouteImport.update({
  id: '/reservation/$id',
  path: '/reservation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentIdRoute = PaymentIdRouteImport.update({
  id: '/payment/$id',
  path: '/payment/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIdRoute = CheckoutIdRouteImport.update({
  id: '/checkout/$id',
  path: '/checkout/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentPrintIdRoute = PaymentPrintIdRouteImport.update({
  id: '/payment/print/$id',
  path: '/payment/print/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/payment/$id': typeof PaymentIdRoute
  '/reservation/$id': typeof ReservationIdRoute
  '/reservation': typeof ReservationIndexRoute
  '/payment/print/$id': typeof PaymentPrintIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/payment/$id': typeof PaymentIdRoute
  '/reservation/$id': typeof ReservationIdRoute
  '/reservation': typeof ReservationIndexRoute
  '/payment/print/$id': typeof PaymentPrintIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/payment/$id': typeof PaymentIdRoute
  '/reservation/$id': typeof ReservationIdRoute
  '/reservation/': typeof ReservationIndexRoute
  '/payment/print/$id': typeof PaymentPrintIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/search'
    | '/checkout/$id'
    | '/payment/$id'
    | '/reservation/$id'
    | '/reservation'
    | '/payment/print/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/search'
    | '/checkout/$id'
    | '/payment/$id'
    | '/reservation/$id'
    | '/reservation'
    | '/payment/print/$id'
  id:
    | '__root__'
    | '/'
    | '/search'
    | '/checkout/$id'
    | '/payment/$id'
    | '/reservation/$id'
    | '/reservation/'
    | '/payment/print/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRoute: typeof SearchRoute
  CheckoutIdRoute: typeof CheckoutIdRoute
  PaymentIdRoute: typeof PaymentIdRoute
  ReservationIdRoute: typeof ReservationIdRoute
  ReservationIndexRoute: typeof ReservationIndexRoute
  PaymentPrintIdRoute: typeof PaymentPrintIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservation/': {
      id: '/reservation/'
      path: '/reservation'
      fullPath: '/reservation'
      preLoaderRoute: typeof ReservationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservation/$id': {
      id: '/reservation/$id'
      path: '/reservation/$id'
      fullPath: '/reservation/$id'
      preLoaderRoute: typeof ReservationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/$id': {
      id: '/payment/$id'
      path: '/payment/$id'
      fullPath: '/payment/$id'
      preLoaderRoute: typeof PaymentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$id': {
      id: '/checkout/$id'
      path: '/checkout/$id'
      fullPath: '/checkout/$id'
      preLoaderRoute: typeof CheckoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/print/$id': {
      id: '/payment/print/$id'
      path: '/payment/print/$id'
      fullPath: '/payment/print/$id'
      preLoaderRoute: typeof PaymentPrintIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRoute: SearchRoute,
  CheckoutIdRoute: CheckoutIdRoute,
  PaymentIdRoute: PaymentIdRoute,
  ReservationIdRoute: ReservationIdRoute,
  ReservationIndexRoute: ReservationIndexRoute,
  PaymentPrintIdRoute: PaymentPrintIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
